{
    'name': "Administració Club Handbol Xàtiva",
    'summary': "Administració Club Handbol Xàtiva",
    'description': """Long description""",
    'author': "Antoni Gimenez",
    'application': True,
    'license': "AGPL-3",
    'website': "http://www.clubhandbolxativa.com",
    'category': 'Uncategorized',
    'version': '11.0.1.0.0',
    'data': ['security/ir.model.access.csv',
             'views/views_cobroPago.xml',
             'views/views_desgrava.xml',
             'views/views_directiva.xml',
             'views/views_empresa.xml',
             'views/views_equip.xml',
             'views/views_esponsor.xml',
             'views/views_factures.xml',
             'views/views_nomina.xml',
             'views/views_persona.xml',
             'views/views_temporada.xml',
             'views/views.xml'
             ],
}
